name: delau
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  custom_radio: ^0.1.2
  flutter_localizations:
    sdk: flutter
  http: ^0.12.0
  validators: ^2.0.0 # change to latest version
  flutter:
    sdk: flutter
  carousel_slider: ^2.2.1
  flutter_launcher_icons: ^0.7.3
  flutter_icons: ^1.0.0
  material_design_icons_flutter: 3.4.4795
  flutter_local_notifications: ^0.9.1
  speech_recognition: ^0.3.0
  flutter_tts: ^0.8.6
  sqflite: any
  path_provider: any
  curved_navigation_bar: ^0.3.1
  permission_handler: ^4.2.0+hotfix.1
  # android_alarm_manager: ^0.4.5+3
  shared_preferences: ^0.5.6
  date_format: ^1.0.8
  firebase_messaging: ^6.0.9
  audioplayers: ^0.14.0
  connectivity: ^0.4.6+2
  flutter_staggered_grid_view: ^0.3.0
  auto_size_text: ^1.1.2
  flutter_speed_dial: ^1.2.5
  flushbar: ^1.9.1
  flutter_star_rating: ^0.0.2
  table_calendar: ^2.2.3
  flutter_svg: ^0.17.3+1
  font_awesome_flutter: ^8.8.1
  bottom_bar_with_sheet: ^0.0.1
  provider: ^4.1.3
  # background_fetch:
  #   git:
  #     url: https://github.com/transistorsoft/flutter_background_fetch
   
  # firebase_messaging: ^4.0.0+1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icon/icon.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/svg/calendar.svg
   - assets/circul1.png
   - assets/postBackground.jpg
   - assets/background/shop.jpg
   - assets/background/working.jpg
   - assets/background/learning.jpg
   - assets/background/meet.jpg
   - assets/background/sport.jpg
   - assets/profile.jpg
   - assets/ramk.png
   - assets/ufo.png
   - assets/pageComing.png
   - assets/demoPage/demoBG.jpg

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-BoldItalic.ttf
        - asset: assets/fonts/Ubuntu-Bold.ttf
        - asset: assets/fonts/Ubuntu-Light.ttf
        - asset: assets/fonts/Ubuntu-LightItalic.ttf
        - asset: assets/fonts/Ubuntu-Medium.ttf
        - asset: assets/fonts/Ubuntu-MediumItalic.ttf
        - asset: assets/fonts/Ubuntu-Regular.ttf
        - asset: assets/fonts/Ubuntu-Italic.ttf
